<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(RepoRoot)src\Common.Dotnet.CsWinRT.props" />
  <Import Project="$(RepoRoot)src\Common.Dotnet.FuzzTest.props" />

  <PropertyGroup>
    <Platforms>x64;ARM64</Platforms>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>$(RepoRoot)$(Platform)\$(Configuration)\tests\ClipPing.FuzzTests\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(RepoRoot)src\settings-ui\Settings.UI.Library\Settings.UI.Library.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="OneFuzzConfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
</Project>
